version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://bun.sh/install | bash
      - export BUN_INSTALL="$HOME/.bun"
      - export PATH="$BUN_INSTALL/bin:$PATH"
  build:
    commands:
      - cd ./frontend
      - bun run build
      - aws s3 sync --delete ./build s3://$BUCKET_NAME
