version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://bun.sh/install | bash
      - export BUN_INSTALL="$HOME/.bun"
      - export PATH="$BUN_INSTALL/bin:$PATH"
      - cd ./frontend
      - bun install
  build:
    commands:
      - bun run build
  post_build:
    commands:
      - aws s3 sync --delete ./dist s3://$BUCKET_NAME
